/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAccountRouteImport } from './routes/app/account'
import { Route as AppBooksRouteImport } from './routes/app/books'
import { Route as AppCertificatesRouteImport } from './routes/app/certificates'
import { Route as AppChaseRouteImport } from './routes/app/chase'
import { Route as AppClerkRouteImport } from './routes/app/clerk'
import { Route as AppRequirementsRouteImport } from './routes/app/requirements'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppVendorsRouteImport } from './routes/app/vendors'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppCertificatesIdRouteImport } from './routes/app/certificates_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppBooksRoute = AppBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificatesRoute = AppCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AppRoute,
} as any)
const AppChaseRoute = AppChaseRouteImport.update({
  id: '/chase',
  path: '/chase',
  getParentRoute: () => AppRoute,
} as any)
const AppClerkRoute = AppClerkRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => AppRoute,
} as any)
const AppRequirementsRoute = AppRequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsRoute = AppVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCertificatesIdRoute = AppCertificatesIdRouteImport.update({
  id: '/certificates_/$id',
  path: '/certificates/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/app/account': typeof AppAccountRoute
  '/app/books': typeof AppBooksRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/chase': typeof AppChaseRoute
  '/app/clerk': typeof AppClerkRoute
  '/app/requirements': typeof AppRequirementsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/vendors': typeof AppVendorsRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/certificates/$id': typeof AppCertificatesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/app/account': typeof AppAccountRoute
  '/app/books': typeof AppBooksRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/chase': typeof AppChaseRoute
  '/app/clerk': typeof AppClerkRoute
  '/app/requirements': typeof AppRequirementsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/vendors': typeof AppVendorsRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/certificates/$id': typeof AppCertificatesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/app/account': typeof AppAccountRoute
  '/app/books': typeof AppBooksRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/chase': typeof AppChaseRoute
  '/app/clerk': typeof AppClerkRoute
  '/app/requirements': typeof AppRequirementsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/vendors': typeof AppVendorsRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/certificates_/$id': typeof AppCertificatesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/demo'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/verify'
    | '/app/account'
    | '/app/books'
    | '/app/certificates'
    | '/app/chase'
    | '/app/clerk'
    | '/app/requirements'
    | '/app/settings'
    | '/app/vendors'
    | '/app/'
    | '/api/auth/$'
    | '/app/certificates/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/verify'
    | '/app/account'
    | '/app/books'
    | '/app/certificates'
    | '/app/chase'
    | '/app/clerk'
    | '/app/requirements'
    | '/app/settings'
    | '/app/vendors'
    | '/app'
    | '/api/auth/$'
    | '/app/certificates/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/demo'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/verify'
    | '/app/account'
    | '/app/books'
    | '/app/certificates'
    | '/app/chase'
    | '/app/clerk'
    | '/app/requirements'
    | '/app/settings'
    | '/app/vendors'
    | '/app/'
    | '/api/auth/$'
    | '/app/certificates_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  VerifyRoute: typeof VerifyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/books': {
      id: '/app/books'
      path: '/books'
      fullPath: '/app/books'
      preLoaderRoute: typeof AppBooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/certificates': {
      id: '/app/certificates'
      path: '/certificates'
      fullPath: '/app/certificates'
      preLoaderRoute: typeof AppCertificatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chase': {
      id: '/app/chase'
      path: '/chase'
      fullPath: '/app/chase'
      preLoaderRoute: typeof AppChaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clerk': {
      id: '/app/clerk'
      path: '/clerk'
      fullPath: '/app/clerk'
      preLoaderRoute: typeof AppClerkRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requirements': {
      id: '/app/requirements'
      path: '/requirements'
      fullPath: '/app/requirements'
      preLoaderRoute: typeof AppRequirementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vendors': {
      id: '/app/vendors'
      path: '/vendors'
      fullPath: '/app/vendors'
      preLoaderRoute: typeof AppVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/certificates_/$id': {
      id: '/app/certificates_/$id'
      path: '/certificates/$id'
      fullPath: '/app/certificates/$id'
      preLoaderRoute: typeof AppCertificatesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppBooksRoute: typeof AppBooksRoute
  AppCertificatesRoute: typeof AppCertificatesRoute
  AppChaseRoute: typeof AppChaseRoute
  AppClerkRoute: typeof AppClerkRoute
  AppRequirementsRoute: typeof AppRequirementsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVendorsRoute: typeof AppVendorsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCertificatesIdRoute: typeof AppCertificatesIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppBooksRoute: AppBooksRoute,
  AppCertificatesRoute: AppCertificatesRoute,
  AppChaseRoute: AppChaseRoute,
  AppClerkRoute: AppClerkRoute,
  AppRequirementsRoute: AppRequirementsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVendorsRoute: AppVendorsRoute,
  AppIndexRoute: AppIndexRoute,
  AppCertificatesIdRoute: AppCertificatesIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  VerifyRoute: VerifyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
